# ultralink_model.jl
# Generated by UltraLink on 2025-03-10T17:35:38.982Z
# This file contains a RxInfer.jl model generated from an UltraLink knowledge graph

using RxInfer, Distributions


@model function ultralink_model()
    # Define variables for entities
    # Entity: alice (type: researcher)
    alice ~ Normal(0.0, 1.0)
    alice_department ~ Categorical([0.5, 0.5])
    alice_publications ~ Poisson(1.0)
    alice_expertise ~ Dirichlet(ones(3))
    alice_yearsExperience ~ Poisson(1.0)
    # Entity: bob (type: researcher)
    bob ~ Normal(0.0, 1.0)
    bob_role ~ Categorical([0.5, 0.5])
    bob_department ~ Categorical([0.5, 0.5])
    bob_publications ~ Poisson(1.0)
    bob_expertise ~ Dirichlet(ones(3))
    bob_yearsExperience ~ Poisson(1.0)
    # Entity: carol (type: researcher)
    carol ~ Normal(0.0, 1.0)
    carol_department ~ Categorical([0.5, 0.5])
    carol_publications ~ Poisson(1.0)
    carol_expertise ~ Dirichlet(ones(3))
    carol_yearsExperience ~ Poisson(1.0)
    # Entity: david (type: researcher)
    david ~ Normal(0.0, 1.0)
    david_role ~ Categorical([0.5, 0.5])
    david_department ~ Categorical([0.5, 0.5])
    david_publications ~ Poisson(1.0)
    david_expertise ~ Dirichlet(ones(3))
    david_yearsExperience ~ Poisson(1.0)
    # Entity: emma (type: researcher)
    emma ~ Normal(0.0, 1.0)
    emma_role ~ Categorical([0.5, 0.5])
    emma_department ~ Categorical([0.5, 0.5])
    emma_publications ~ Poisson(1.0)
    emma_expertise ~ Dirichlet(ones(3))
    emma_yearsExperience ~ Poisson(1.0)
    # Entity: frank (type: researcher)
    frank ~ Normal(0.0, 1.0)
    frank_role ~ Categorical([0.5, 0.5])
    frank_department ~ Categorical([0.5, 0.5])
    frank_publications ~ Poisson(1.0)
    frank_expertise ~ Dirichlet(ones(3))
    frank_yearsExperience ~ Poisson(1.0)
    # Entity: grace (type: researcher)
    grace ~ Normal(0.0, 1.0)
    grace_role ~ Categorical([0.5, 0.5])
    grace_department ~ Categorical([0.5, 0.5])
    grace_publications ~ Beta(1.0, 1.0)
    grace_expertise ~ Dirichlet(ones(3))
    grace_yearsExperience ~ Poisson(1.0)
    # Entity: active-inference-model (type: project)
    active_inference_model ~ Normal(0.0, 1.0)
    active_inference_model_status ~ Categorical([0.5, 0.5])
    active_inference_model_startDate ~ Categorical([0.5, 0.5])
    active_inference_model_endDate ~ Categorical([0.5, 0.5])
    active_inference_model_funding ~ Poisson(1.0)
    # Entity: ant-colony-study (type: project)
    ant_colony_study ~ Normal(0.0, 1.0)
    ant_colony_study_status ~ Categorical([0.5, 0.5])
    ant_colony_study_startDate ~ Categorical([0.5, 0.5])
    ant_colony_study_endDate ~ Categorical([0.5, 0.5])
    ant_colony_study_funding ~ Poisson(1.0)
    ant_colony_study_fundingSource ~ Categorical([0.5, 0.5])
    # Entity: neural-basis (type: project)
    neural_basis ~ Normal(0.0, 1.0)
    neural_basis_status ~ Categorical([0.5, 0.5])
    neural_basis_startDate ~ Categorical([0.5, 0.5])
    neural_basis_endDate ~ Categorical([0.5, 0.5])
    neural_basis_funding ~ Poisson(1.0)
    neural_basis_fundingSource ~ Categorical([0.5, 0.5])
    # Entity: active-inference (type: concept)
    active_inference ~ Dirichlet([1.0, 1.0, 1.0])
    active_inference_keyPapers ~ Dirichlet(ones(2))
    # Entity: collective-behavior (type: concept)
    collective_behavior ~ Dirichlet([1.0, 1.0, 1.0])
    collective_behavior_field ~ Categorical([0.5, 0.5])
    collective_behavior_keyPapers ~ Dirichlet(ones(1))
    # Entity: swarm-intelligence (type: concept)
    swarm_intelligence ~ Dirichlet([1.0, 1.0, 1.0])
    swarm_intelligence_field ~ Categorical([0.5, 0.5])
    swarm_intelligence_keyPapers ~ Dirichlet(ones(1))
    # Entity: ant-tracking (type: equipment)
    ant_tracking ~ Normal(0.0, 1.0)
    ant_tracking_type ~ Categorical([0.5, 0.5])
    ant_tracking_status ~ Categorical([0.5, 0.5])
    ant_tracking_location ~ Categorical([0.5, 0.5])
    ant_tracking_cost ~ Poisson(1.0)
    ant_tracking_purchaseDate ~ Categorical([0.5, 0.5])
    ant_tracking_maintenanceSchedule ~ Categorical([0.5, 0.5])
    # Entity: neural-recording (type: equipment)
    neural_recording ~ Normal(0.0, 1.0)
    neural_recording_type ~ Categorical([0.5, 0.5])
    neural_recording_status ~ Categorical([0.5, 0.5])
    neural_recording_location ~ Categorical([0.5, 0.5])
    neural_recording_cost ~ Poisson(1.0)
    neural_recording_purchaseDate ~ Categorical([0.5, 0.5])
    neural_recording_maintenanceSchedule ~ Categorical([0.5, 0.5])
    # Entity: computation-cluster (type: equipment)
    computation_cluster ~ Normal(0.0, 1.0)
    computation_cluster_type ~ Categorical([0.5, 0.5])
    computation_cluster_status ~ Categorical([0.5, 0.5])
    computation_cluster_location ~ Categorical([0.5, 0.5])
    computation_cluster_cost ~ Poisson(1.0)
    computation_cluster_purchaseDate ~ Categorical([0.5, 0.5])
    computation_cluster_maintenanceSchedule ~ Categorical([0.5, 0.5])
    # Entity: paper-2023a (type: publication)
    paper_2023a ~ Normal(0.0, 1.0)
    paper_2023a_authors ~ Dirichlet(ones(3))
    paper_2023a_year ~ Poisson(1.0)
    paper_2023a_citations ~ Poisson(1.0)
    # Entity: paper-2023b (type: publication)
    paper_2023b ~ Normal(0.0, 1.0)
    paper_2023b_authors ~ Dirichlet(ones(3))
    paper_2023b_journal ~ Categorical([0.5, 0.5])
    paper_2023b_year ~ Poisson(1.0)
    paper_2023b_citations ~ Poisson(1.0)
    # Entity: paper-2024 (type: publication)
    paper_2024 ~ Normal(0.0, 1.0)
    paper_2024_authors ~ Dirichlet(ones(3))
    paper_2024_year ~ Poisson(1.0)
    paper_2024_citations ~ Poisson(1.0)

    # Define relationships between variables
    # Relationship: alice (leads) active-inference-model-leads
    active_inference_model_leads ~ Normal(0.1 * alice, 1.0)
    alice_leads_active_inference_model_leads_role ~ Categorical([0.5, 0.5])
    alice_leads_active_inference_model_leads_timeCommitment ~ Beta(1.0, 1.0)
    # Relationship: alice (mentors) david-mentors
    david_mentors ~ Normal(0.1 * alice, 1.0)
    alice_mentors_david_mentors_type ~ Categorical([0.5, 0.5])
    alice_mentors_david_mentors_startDate ~ Categorical([0.5, 0.5])
    # Relationship: alice (mentors) carol-mentors
    carol_mentors ~ Normal(0.1 * alice, 1.0)
    alice_mentors_carol_mentors_type ~ Categorical([0.5, 0.5])
    alice_mentors_carol_mentors_startDate ~ Categorical([0.5, 0.5])
    # Relationship: alice (authored) paper-2023a-authored
    paper_2023a_authored ~ Normal(0.1 * alice, 1.0)
    alice_authored_paper_2023a_authored_contributionType ~ Categorical([0.5, 0.5])
    alice_authored_paper_2023a_authored_contributionPercentage ~ Poisson(1.0)
    # Relationship: alice (authored) paper-2024-authored
    paper_2024_authored ~ Normal(0.1 * alice, 1.0)
    alice_authored_paper_2024_authored_contributionType ~ Categorical([0.5, 0.5])
    alice_authored_paper_2024_authored_contributionPercentage ~ Poisson(1.0)
    # Relationship: bob (leads) ant-colony-study-leads
    ant_colony_study_leads ~ Normal(0.1 * bob, 1.0)
    bob_leads_ant_colony_study_leads_role ~ Categorical([0.5, 0.5])
    bob_leads_ant_colony_study_leads_timeCommitment ~ Beta(1.0, 1.0)
    # Relationship: bob (contributes_to) active-inference-model-contributes_to
    active_inference_model_contributes_to ~ Normal(0.1 * bob, 1.0)
    bob_contributes_to_active_inference_model_contributes_to_role ~ Categorical([0.5, 0.5])
    bob_contributes_to_active_inference_model_contributes_to_startDate ~ Categorical([0.5, 0.5])
    # Relationship: bob (mentors) emma-mentors
    emma_mentors ~ Normal(0.1 * bob, 1.0)
    bob_mentors_emma_mentors_type ~ Categorical([0.5, 0.5])
    bob_mentors_emma_mentors_startDate ~ Categorical([0.5, 0.5])
    # Relationship: bob (authored) paper-2023a-authored
    paper_2023a_authored ~ Normal(0.1 * bob, 1.0)
    bob_authored_paper_2023a_authored_contributionType ~ Categorical([0.5, 0.5])
    bob_authored_paper_2023a_authored_contributionPercentage ~ Poisson(1.0)
    # Relationship: bob (authored) paper-2023b-authored
    paper_2023b_authored ~ Normal(0.1 * bob, 1.0)
    bob_authored_paper_2023b_authored_contributionType ~ Categorical([0.5, 0.5])
    bob_authored_paper_2023b_authored_contributionPercentage ~ Poisson(1.0)
    # Relationship: bob (authored) paper-2024-authored
    paper_2024_authored ~ Normal(0.1 * bob, 1.0)
    bob_authored_paper_2024_authored_contributionType ~ Categorical([0.5, 0.5])
    bob_authored_paper_2024_authored_contributionPercentage ~ Poisson(1.0)
    # Relationship: carol (contributes) active-inference-model-contributes
    active_inference_model_contributes ~ Normal(0.1 * carol, 1.0)
    carol_contributes_active_inference_model_contributes_role ~ Categorical([0.5, 0.5])
    carol_contributes_active_inference_model_contributes_timeCommitment ~ Beta(1.0, 1.0)
    # Relationship: carol (contributes_to) active-inference-model-contributes_to
    active_inference_model_contributes_to ~ Normal(0.1 * carol, 1.0)
    carol_contributes_to_active_inference_model_contributes_to_role ~ Categorical([0.5, 0.5])
    carol_contributes_to_active_inference_model_contributes_to_startDate ~ Categorical([0.5, 0.5])
    # Relationship: carol (reports_to) alice-reports_to
    alice_reports_to ~ Normal(0.1 * carol, 1.0)
    carol_reports_to_alice_reports_to_startDate ~ Categorical([0.5, 0.5])
    # Relationship: carol (authored) paper-2023a-authored
    paper_2023a_authored ~ Normal(0.1 * carol, 1.0)
    carol_authored_paper_2023a_authored_contributionType ~ Categorical([0.5, 0.5])
    carol_authored_paper_2023a_authored_contributionPercentage ~ Poisson(1.0)
    # Relationship: carol (authored) paper-2024-authored
    paper_2024_authored ~ Normal(0.1 * carol, 1.0)
    carol_authored_paper_2024_authored_contributionType ~ Categorical([0.5, 0.5])
    carol_authored_paper_2024_authored_contributionPercentage ~ Poisson(1.0)
    # Relationship: david (contributes) active-inference-model-contributes
    active_inference_model_contributes ~ Normal(0.1 * david, 1.0)
    david_contributes_active_inference_model_contributes_role ~ Categorical([0.5, 0.5])
    david_contributes_active_inference_model_contributes_timeCommitment ~ Beta(1.0, 1.0)
    # Relationship: david (contributes_to) ant-colony-study-contributes_to
    ant_colony_study_contributes_to ~ Normal(0.1 * david, 1.0)
    david_contributes_to_ant_colony_study_contributes_to_role ~ Categorical([0.5, 0.5])
    david_contributes_to_ant_colony_study_contributes_to_startDate ~ Categorical([0.5, 0.5])
    david_contributes_to_ant_colony_study_contributes_to_timeCommitment ~ Categorical([0.5, 0.5])
    # Relationship: david (reports_to) bob-reports_to
    bob_reports_to ~ Normal(0.1 * david, 1.0)
    david_reports_to_bob_reports_to_startDate ~ Categorical([0.5, 0.5])
    # Relationship: david (authored) paper-2024-authored
    paper_2024_authored ~ Normal(0.1 * david, 1.0)
    david_authored_paper_2024_authored_contributionType ~ Categorical([0.5, 0.5])
    david_authored_paper_2024_authored_contributionPercentage ~ Poisson(1.0)
    # Relationship: emma (contributes) ant-colony-study-contributes
    ant_colony_study_contributes ~ Normal(0.1 * emma, 1.0)
    emma_contributes_ant_colony_study_contributes_role ~ Categorical([0.5, 0.5])
    emma_contributes_ant_colony_study_contributes_timeCommitment ~ Beta(1.0, 1.0)
    # Relationship: emma (contributes_to) ant-colony-study-contributes_to
    ant_colony_study_contributes_to ~ Normal(0.1 * emma, 1.0)
    emma_contributes_to_ant_colony_study_contributes_to_role ~ Categorical([0.5, 0.5])
    emma_contributes_to_ant_colony_study_contributes_to_startDate ~ Categorical([0.5, 0.5])
    # Relationship: emma (reports_to) alice-reports_to
    alice_reports_to ~ Normal(0.1 * emma, 1.0)
    emma_reports_to_alice_reports_to_startDate ~ Categorical([0.5, 0.5])
    # Relationship: emma (authored) paper-2023b-authored
    paper_2023b_authored ~ Normal(0.1 * emma, 1.0)
    emma_authored_paper_2023b_authored_contributionType ~ Categorical([0.5, 0.5])
    emma_authored_paper_2023b_authored_contributionPercentage ~ Poisson(1.0)
    # Relationship: frank (contributes) ant-colony-study-contributes
    ant_colony_study_contributes ~ Normal(0.1 * frank, 1.0)
    frank_contributes_ant_colony_study_contributes_role ~ Categorical([0.5, 0.5])
    frank_contributes_ant_colony_study_contributes_timeCommitment ~ Beta(1.0, 1.0)
    # Relationship: frank (contributes_to) ant-colony-study-contributes_to
    ant_colony_study_contributes_to ~ Normal(0.1 * frank, 1.0)
    frank_contributes_to_ant_colony_study_contributes_to_role ~ Categorical([0.5, 0.5])
    frank_contributes_to_ant_colony_study_contributes_to_startDate ~ Categorical([0.5, 0.5])
    # Relationship: frank (co_advises) emma-co_advises
    emma_co_advises ~ Normal(0.1 * frank, 1.0)
    frank_co_advises_emma_co_advises_startDate ~ Categorical([0.5, 0.5])
    # Relationship: frank (authored) paper-2023b-authored
    paper_2023b_authored ~ Normal(0.1 * frank, 1.0)
    frank_authored_paper_2023b_authored_contributionType ~ Categorical([0.5, 0.5])
    frank_authored_paper_2023b_authored_contributionPercentage ~ Poisson(1.0)
    # Relationship: grace (contributes_to) ant-colony-study-contributes_to
    ant_colony_study_contributes_to ~ Normal(0.1 * grace, 1.0)
    grace_contributes_to_ant_colony_study_contributes_to_role ~ Categorical([0.5, 0.5])
    grace_contributes_to_ant_colony_study_contributes_to_startDate ~ Categorical([0.5, 0.5])
    # Relationship: grace (reports_to) bob-reports_to
    bob_reports_to ~ Normal(0.1 * grace, 1.0)
    grace_reports_to_bob_reports_to_startDate ~ Categorical([0.5, 0.5])
    # Relationship: grace (authored) paper-2024-authored
    paper_2024_authored ~ Normal(0.1 * grace, 1.0)
    grace_authored_paper_2024_authored_contributionType ~ Categorical([0.5, 0.5])
    grace_authored_paper_2024_authored_contributionPercentage ~ Poisson(1.0)
    # Relationship: active-inference-model (applies) active-inference-applies
    active_inference_applies ~ Normal(0.1 * active_inference_model, 1.0)
    active_inference_model_applies_active_inference_applies_centrality ~ Categorical([0.5, 0.5])
    active_inference_model_applies_active_inference_applies_innovation ~ Categorical([0.5, 0.5])
    # Relationship: active-inference-model (uses) computation-cluster-uses
    computation_cluster_uses ~ Normal(0.1 * active_inference_model, 1.0)
    active_inference_model_uses_computation_cluster_uses_frequency ~ Categorical([0.5, 0.5])
    active_inference_model_uses_computation_cluster_uses_priority ~ Categorical([0.5, 0.5])
    # Relationship: ant-colony-study (applies) collective-behavior-applies
    collective_behavior_applies ~ Normal(0.1 * ant_colony_study, 1.0)
    ant_colony_study_applies_collective_behavior_applies_centrality ~ Categorical([0.5, 0.5])
    ant_colony_study_applies_collective_behavior_applies_innovation ~ Categorical([0.5, 0.5])
    # Relationship: ant-colony-study (uses) ant-tracking-uses
    ant_tracking_uses ~ Normal(0.1 * ant_colony_study, 1.0)
    ant_colony_study_uses_ant_tracking_uses_frequency ~ Categorical([0.5, 0.5])
    ant_colony_study_uses_ant_tracking_uses_priority ~ Categorical([0.5, 0.5])
    # Relationship: active-inference (relates_to) collective-behavior-relates_to
    collective_behavior_relates_to ~ Normal(0.1 * active_inference, 1.0)
    active_inference_relates_to_collective_behavior_relates_to_relationship ~ Categorical([0.5, 0.5])
    active_inference_relates_to_collective_behavior_relates_to_strength ~ Categorical([0.5, 0.5])
    # Relationship: neural-basis (uses) neural-recording-uses
    neural_recording_uses ~ Normal(0.1 * neural_basis, 1.0)
    neural_basis_uses_neural_recording_uses_frequency ~ Categorical([0.5, 0.5])
    neural_basis_uses_neural_recording_uses_priority ~ Categorical([0.5, 0.5])
    # Relationship: paper-2023a (results_from) active-inference-model-results_from
    active_inference_model_results_from ~ Normal(0.1 * paper_2023a, 1.0)
    paper_2023a_results_from_active_inference_model_results_from_contribution ~ Categorical([0.5, 0.5])
    # Relationship: paper-2023a (discusses) active-inference-discusses
    active_inference_discusses ~ Normal(0.1 * paper_2023a, 1.0)
    paper_2023a_discusses_active_inference_discusses_depth ~ Categorical([0.5, 0.5])
    # Relationship: paper-2023b (results_from) ant-colony-study-results_from
    ant_colony_study_results_from ~ Normal(0.1 * paper_2023b, 1.0)
    paper_2023b_results_from_ant_colony_study_results_from_contribution ~ Categorical([0.5, 0.5])
    # Relationship: paper-2023b (discusses) collective-behavior-discusses
    collective_behavior_discusses ~ Normal(0.1 * paper_2023b, 1.0)
    paper_2023b_discusses_collective_behavior_discusses_depth ~ Categorical([0.5, 0.5])
    # Relationship: paper-2024 (results_from) active-inference-model-results_from
    active_inference_model_results_from ~ Normal(0.1 * paper_2024, 1.0)
    paper_2024_results_from_active_inference_model_results_from_contribution ~ Categorical([0.5, 0.5])
    # Relationship: paper-2024 (results_from) ant-colony-study-results_from
    ant_colony_study_results_from ~ Normal(0.1 * paper_2024, 1.0)
    paper_2024_results_from_ant_colony_study_results_from_contribution ~ Categorical([0.5, 0.5])
    # Relationship: paper-2024 (discusses) swarm-intelligence-discusses
    swarm_intelligence_discusses ~ Normal(0.1 * paper_2024, 1.0)
    paper_2024_discusses_swarm_intelligence_discusses_depth ~ Categorical([0.5, 0.5])

    # Return variables of interest
    return (alice, bob, carol, david, emma, frank, grace, active_inference_model, ant_colony_study, neural_basis, active_inference, collective_behavior, swarm_intelligence, ant_tracking, neural_recording, computation_cluster, paper_2023a, paper_2023b, paper_2024)
end

# Test script for ultralink_model

function test_ultralink_model()
    # Create the model
    model = ultralink_model()

    # Run inference
    result = infer(
        model = model,
        data = (
            alice = rand(Normal(0.0, 1.0)),
            bob = rand(Normal(0.0, 1.0)),
            carol = rand(Normal(0.0, 1.0)),
        )
    )

    # Access posterior distributions
    posterior_alice = result.posteriors[:alice]
    posterior_bob = result.posteriors[:bob]
    posterior_carol = result.posteriors[:carol]

    return result
end

# Run the test
test_ultralink_model()